---
roles:
  - name: buluma.bootstrap
  - name: buluma.apache
  - name: buluma.cron
  - name: buluma.service
  - name: buluma.systemd
  - name: buluma.python_pip
  - name: buluma.reboot
collections:
  - name: ansible.posix
  - name: community.aws
