---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include variables for Amazon Linux.
  include_vars: "AmazonLinux.yml"
  when:
    - ansible_distribution == "Amazon"
    - ansible_distribution_major_version == "NA"

- name: Define apache_packages.
  ansible.builtin.set_fact:
    apache_packages: "{{ __apache_packages | list }}"
  when: apache_packages is not defined

# Setup/install.
- name: Setup.
  include_tasks: "setup-{{ ansible_os_family }}.yml"

# Configure.
- name: Configure.
  include_tasks: "configure-{{ ansible_os_family }}.yml"

- name: create random but idempotent password
  set_fact:
    password: "{{ lookup('password', '/dev/null', seed=inventory_hostname) }}"

# find module
- name: Test if connection still exists
  ansible.builtin.ping:
