---
- name: prepare
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: buluma.bootstrap
    - role: buluma.cron
    - role: buluma.service
    # - role: buluma.gitlab
    # - role: buluma.apache
